### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by aliceathens** [react-native-component/react-native-smart-splash-screen#49]
OS: 8.0
Device: OnePlus3

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference
       at com.reactnativecomponent.splashscreen.RCTSplashScreen.getActivity(RCTSplashScreen.java:31)
       at com.reactnativecomponent.splashscreen.RCTSplashScreen.removeSplashScreen(RCTSplashScreen.java:82)
       at com.reactnativecomponent.splashscreen.RCTSplashScreenModule$1.run(RCTSplashScreenModule.java:56)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
       at java.lang.Thread.run(Thread.java:764)`

**Comment by webraptor** [comment]
We're also experiencing this issue on about 10% of android devices

**Comment by aliceathens** [comment]
Yes still an issue with about the same amount of users

**Comment by webraptor** [comment]
We've managed to narrow this down to a particular use case, when the app is started for a received push notification (when the splashscreen's not shown but we try to close it, resulting in the null pointer exception)

Created a PR with the fix: https://github.com/react-native-component/react-native-smart-splash-screen/pull/56

**Comment by aliceathens** [comment]
Great! Would be good to get this pull request merged this issue is the only one causing our app to crash on Android.
